# Generated by Django 3.1 on 2020-08-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_email', '0004_throttling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaildevice',
            name='name',
        ),
    ]
